version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_USER: postgresUser
      POSTGRES_DB: 'postgresDB'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"
    networks:
      - node-app
    volumes:
      - db:/var/lib/postgresql/data
  nest-auth:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    links:
      - db
    networks:
      - node-app
networks:
  node-app:
    driver: bridge

volumes:
  db:
    driver: local
