version: '3'
services:
  rabbitmq: 
    image: 
  nest-email:
    volumes:
      - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: '../email-service/Dockerfile'
    networks:
      - node-app
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - node-app
    volumes:
      - db:/var/lib/postgresql/data
  nest-auth:
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - db
    networks:
      - node-app
networks:
  node-app:
    driver: bridge

volumes:
  db:
    driver: local
